"""create initial schema

Revision ID: 748517d6d376
Revises: 
Create Date: 2026-09-05 14:50:02.739353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '748517d6d376'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_raw',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_table('pipeline_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('games_collected', sa.Integer(), nullable=False),
    sa.Column('games_new', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('games',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('is_dlc', sa.Boolean(), nullable=False),
    sa.Column('review_score_pct', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('owners_low', sa.Integer(), nullable=True),
    sa.Column('owners_high', sa.Integer(), nullable=True),
    sa.Column('avg_playtime_min', sa.Integer(), nullable=True),
    sa.Column('cohort_genre', sa.String(), nullable=False),
    sa.Column('cohort_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['games_raw.app_id'], ),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_table('game_scores',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('quality_pctile', sa.Float(), nullable=False),
    sa.Column('exposure_pctile', sa.Float(), nullable=False),
    sa.Column('hidden_gem_score', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['games.app_id'], ),
    sa.PrimaryKeyConstraint('app_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_scores')
    op.drop_table('games')
    op.drop_table('pipeline_runs')
    op.drop_table('games_raw')
    # ### end Alembic commands ###
